<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistique pour l'expérimentation animale – dispo_expe</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Statistique pour l’expérimentation animale</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Introduction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Dispo_expe.html" rel="" target="" aria-current="page">
 <span class="menu-text">Dispositif expérimental</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./lme.qmd" rel="" target="">
 <span class="menu-text">Modèle linéaire Mixte</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#règle-des-3r-en-expérimentation-animale" id="toc-règle-des-3r-en-expérimentation-animale" class="nav-link active" data-scroll-target="#règle-des-3r-en-expérimentation-animale">Règle des 3R en expérimentation animale</a>
  <ul class="collapse">
  <li><a href="#réduire" id="toc-réduire" class="nav-link" data-scroll-target="#réduire">Réduire</a></li>
  <li><a href="#remplacer" id="toc-remplacer" class="nav-link" data-scroll-target="#remplacer">Remplacer</a></li>
  <li><a href="#raffiner" id="toc-raffiner" class="nav-link" data-scroll-target="#raffiner">Raffiner</a></li>
  </ul></li>
  <li><a href="#dispositifs-expérimentaux" id="toc-dispositifs-expérimentaux" class="nav-link" data-scroll-target="#dispositifs-expérimentaux">Dispositifs expérimentaux</a></li>
  <li><a href="#plans-à-mesures-répétées" id="toc-plans-à-mesures-répétées" class="nav-link" data-scroll-target="#plans-à-mesures-répétées">Plans à mesures répétées</a>
  <ul class="collapse">
  <li><a href="#généralités" id="toc-généralités" class="nav-link" data-scroll-target="#généralités">Généralités</a></li>
  </ul></li>
  <li><a href="#etude-longitudinale" id="toc-etude-longitudinale" class="nav-link" data-scroll-target="#etude-longitudinale">Etude longitudinale</a>
  <ul class="collapse">
  <li><a href="#exemple" id="toc-exemple" class="nav-link" data-scroll-target="#exemple">Exemple</a></li>
  </ul></li>
  <li><a href="#etude-de-type-crossover" id="toc-etude-de-type-crossover" class="nav-link" data-scroll-target="#etude-de-type-crossover">Etude de type crossover</a>
  <ul class="collapse">
  <li><a href="#exemple-1" id="toc-exemple-1" class="nav-link" data-scroll-target="#exemple-1">Exemple :</a></li>
  </ul></li>
  <li><a href="#etudes-à-effets-imbriqués" id="toc-etudes-à-effets-imbriqués" class="nav-link" data-scroll-target="#etudes-à-effets-imbriqués">Etudes à effets imbriqués</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#exemple-2" id="toc-exemple-2" class="nav-link" data-scroll-target="#exemple-2">Exemple :</a></li>
  </ul></li>
  <li><a href="#etudes-de-type-split-plot" id="toc-etudes-de-type-split-plot" class="nav-link" data-scroll-target="#etudes-de-type-split-plot">Etudes de type SPLIT-PLOT</a>
  <ul class="collapse">
  <li><a href="#mise-en-oeuvre" id="toc-mise-en-oeuvre" class="nav-link" data-scroll-target="#mise-en-oeuvre">Mise en oeuvre</a></li>
  <li><a href="#exemple-3" id="toc-exemple-3" class="nav-link" data-scroll-target="#exemple-3">Exemple :</a></li>
  </ul></li>
  <li><a href="#rappel-anova-sur-données-indépendantes" id="toc-rappel-anova-sur-données-indépendantes" class="nav-link" data-scroll-target="#rappel-anova-sur-données-indépendantes">Rappel ANOVA sur données indépendantes</a>
  <ul class="collapse">
  <li><a href="#modélisation-1-anova-sur-mesures-indépendantes-aggrégation-des-données-sur-time" id="toc-modélisation-1-anova-sur-mesures-indépendantes-aggrégation-des-données-sur-time" class="nav-link" data-scroll-target="#modélisation-1-anova-sur-mesures-indépendantes-aggrégation-des-données-sur-time">Modélisation 1 : ANOVA sur mesures indépendantes (aggrégation des données sur Time)</a>
  <ul class="collapse">
  <li><a href="#le-modèle-mathématique-et-les-hypothèses-des-tests" id="toc-le-modèle-mathématique-et-les-hypothèses-des-tests" class="nav-link" data-scroll-target="#le-modèle-mathématique-et-les-hypothèses-des-tests">Le modèle mathématique et les hypothèses des tests</a></li>
  <li><a href="#etude-de-leffet-régime-sur-bw" id="toc-etude-de-leffet-régime-sur-bw" class="nav-link" data-scroll-target="#etude-de-leffet-régime-sur-bw">Etude de l’effet régime sur BW</a></li>
  <li><a href="#etude-de-leffet-régime-sur-la-variable-insulinemia" id="toc-etude-de-leffet-régime-sur-la-variable-insulinemia" class="nav-link" data-scroll-target="#etude-de-leffet-régime-sur-la-variable-insulinemia">Etude de l’effet régime sur la variable Insulinemia</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#modélisation-à-effets-mixtes" id="toc-modélisation-à-effets-mixtes" class="nav-link" data-scroll-target="#modélisation-à-effets-mixtes">Modélisation à effets mixtes</a>
  <ul class="collapse">
  <li><a href="#etude-de-leffet-temporel-dans-létude-sur-les-rats" id="toc-etude-de-leffet-temporel-dans-létude-sur-les-rats" class="nav-link" data-scroll-target="#etude-de-leffet-temporel-dans-létude-sur-les-rats">Etude de l’effet temporel dans l’étude sur les rats</a>
  <ul class="collapse">
  <li><a href="#variable-réponse-bw" id="toc-variable-réponse-bw" class="nav-link" data-scroll-target="#variable-réponse-bw">Variable réponse BW</a></li>
  </ul></li>
  <li><a href="#anova-à-deux-facteurs-fixes-et-un-facteur-aléatoire" id="toc-anova-à-deux-facteurs-fixes-et-un-facteur-aléatoire" class="nav-link" data-scroll-target="#anova-à-deux-facteurs-fixes-et-un-facteur-aléatoire">ANOVA à deux facteurs fixes et un facteur aléatoire</a></li>
  <li><a href="#effet-sur-insulinemia" id="toc-effet-sur-insulinemia" class="nav-link" data-scroll-target="#effet-sur-insulinemia">Effet sur insulinemia</a></li>
  </ul></li>
  <li><a href="#anova-à-effets-imbriqués" id="toc-anova-à-effets-imbriqués" class="nav-link" data-scroll-target="#anova-à-effets-imbriqués">ANOVA à effets imbriqués</a></li>
  <li><a href="#anova-split-plot" id="toc-anova-split-plot" class="nav-link" data-scroll-target="#anova-split-plot">Anova split-plot</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">



<section id="règle-des-3r-en-expérimentation-animale" class="level1">
<h1>Règle des 3R en expérimentation animale</h1>
<ul>
<li><p>Elaborée en 1959, née de la réflexion éthique de Russel W. et Burch R., appliquée à l’expérimentation animale en Europe et Amérique du Nord.</p></li>
<li><p>3 R : Réduire, Remplacer, Raffiner.</p></li>
</ul>
<section id="réduire" class="level2">
<h2 class="anchored" data-anchor-id="réduire">Réduire</h2>
<p>Objectif : diminuer le nombre d’animaux utilisés en recherche :</p>
<ul>
<li><p>aux expériences absolument indispensables</p></li>
<li><p>Ne pas répéter des expériences antérieures</p></li>
</ul>
<p>Moyen : Rédiger un protocole expérimental avant l’expérience.</p>
</section>
<section id="remplacer" class="level2">
<h2 class="anchored" data-anchor-id="remplacer">Remplacer</h2>
<ul>
<li><p>Travailler sur des cellules ou des tissus (IN VITRO)</p></li>
<li><p>Simuler numériquement (IN SILICO) les maladies et leur développement <span class="math inline">\(\leadsto\)</span> approche encore imparfaite vue la compléxité du fonctionnement biologique.</p></li>
</ul>
</section>
<section id="raffiner" class="level2">
<h2 class="anchored" data-anchor-id="raffiner">Raffiner</h2>
<p>Optimiser l’expérimentation pour réduire, supprimer ou soulager la douleur ou la détresse, et ainsi d’améliorer le bien-être des animaux utilisés.</p>
<p>D’un point de vue statistique, le recours aux plans d’expérience va permettre de contribuer aux 3R.</p>
</section>
</section>
<section id="dispositifs-expérimentaux" class="level1">
<h1>Dispositifs expérimentaux</h1>
<p>Pour tester l’effet d’un traitement, on utilise des plans expérimentaux. Il s’agit d’un ensemble de méthodes pour</p>
<ul>
<li><p>planifier des expériences,</p></li>
<li><p>analyser les résultats expérimentaux.</p></li>
</ul>
<p>Ils peuvent s’appliquer dans de nombreux domaines (optimisation de produits, effet d’un traitement, changement de process, …).</p>
<p>Un dispositif expérimental est un système dans lequel</p>
<ul>
<li><p>On a une ou plusieurs réponses,</p></li>
<li><p>qui dépendent d’un certain nombre de facteurs (contrôlés ou non contrôlés).</p></li>
</ul>
<p>L’objectif est d’intégrer (contrôler) le maximum de facteurs simultanément dans l’analyse et de réduire le “poids” des facteurs non contrôlés (résidu).</p>
<p>La précision des résultats obtenus dépendra du nombre d’expérience mais aussi de l’organisation de ces plans.</p>
<ul>
<li><p>Dans les précédents cours, les plans à mesures indépendantes ont été présentés, ici on va présenter deux autres types de plans qui serviront d’exemples dans la suite du cours.</p></li>
<li><p>Les nouveaux modèles statistiques qui seront présentés par la suite seront adaptés pour traiter ce type de données.</p></li>
</ul>
<p>De façon générique le traitement ou l’exposition désignera le (ou les) facteur(s) d’intérêt.</p>
</section>
<section id="plans-à-mesures-répétées" class="level1">
<h1>Plans à mesures répétées</h1>
<section id="généralités" class="level2">
<h2 class="anchored" data-anchor-id="généralités">Généralités</h2>
<p>Dans un plan d’expérience à mesures répétées, un même sujet est mesuré sous chacun des niveaux d’un traitement.</p>
<p>Objectifs :</p>
<ul>
<li><p>Meilleur contrôle des différences individuelles entre les sujets.</p></li>
<li><p>Réduire l’erreur expérimentale, la variabilité due aux différences individuelles.</p></li>
</ul>
<p>Dans ce type de dispositif on considère souvent un facteur BETWEEN (inter-individuel) qui permet d’étudier si l’effet du traitement (ou de l’exposition) est différent selon le niveau de ce facteur BETWEEN.</p>
</section>
</section>
<section id="etude-longitudinale" class="level1">
<h1>Etude longitudinale</h1>
<ul>
<li><p>Suivi d’une population (ou d’un phénomène) dans le temps.</p></li>
<li><p>Au moins deux périodes distinctes avec des sujets identiques.</p></li>
</ul>
<section id="exemple" class="level2">
<h2 class="anchored" data-anchor-id="exemple">Exemple</h2>
<p>Une étude de l’école avait pour objectif de contrôler l’effet au cours du temps de 4 régimes alimentaires sur les paramètres biochimiques liés au contrôle de l’obésité.</p>
<p>On constitue 4 groupes de 6 rats :</p>
<ul>
<li><p>un groupe contrôle (CC),</p></li>
<li><p>un groupe recevant un régime enrichi en lipide (LL),</p></li>
<li><p>un régime enrichi en fructose (FF)</p></li>
<li><p>un enrichi en lipide et fructose (LF).</p></li>
</ul>
<p>Les variables réponses sont les suivantes :</p>
<ul>
<li><p>Body Weigth ( poids corporel),</p></li>
<li><p>Masse grasse corporelle,</p></li>
<li><p>Glycémie,</p></li>
<li><p>Insulinémie,</p></li>
<li><p>Taux de cholestérol,</p></li>
<li><p>Taux de triglycérides,</p></li>
<li><p>Non Esterified Fatty Acid.</p></li>
</ul>
<p>Toutes les données sont mesurées au bout d’une semaine (Week1) puis de 11 (Week11).</p>
<p>Les données sont disponibles ici : <a href="data1.xlsx">data1</a></p>
<p>Le plan d’expérience peut être résumé par la figure suivante :</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/plan1.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">figure 1</figcaption>
</figure>
</div>
<p>Un extrait des données recueillies :</p>
<p>On étudie</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>rats <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data1.xlsx"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>rats<span class="sc">$</span>Groups<span class="ot">&lt;-</span><span class="fu">factor</span>(rats<span class="sc">$</span>Groups,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"CC"</span>,<span class="st">"LL"</span>,<span class="st">"FF"</span>,<span class="st">"LF"</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="st">"CC"</span>,<span class="st">"LL"</span>,<span class="st">"FF"</span>,<span class="st">"LF"</span>))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>rats<span class="sc">$</span>Time<span class="ot">&lt;-</span><span class="fu">factor</span>(rats<span class="sc">$</span>Time,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"Week 1"</span>,<span class="st">"Week 11"</span>))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(rats),<span class="at">digits=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Rats</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Groups</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Time</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BW</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">body fat</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Glycemia</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Insulinemia</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Cholesterol</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">TG</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">NEFA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">CC</td>
<td style="text-align: left;">Week 1</td>
<td style="text-align: right;">385.4</td>
<td style="text-align: right;">44.58</td>
<td style="text-align: right;">5.13</td>
<td style="text-align: right;">2.41</td>
<td style="text-align: right;">1.31</td>
<td style="text-align: right;">1.83</td>
<td style="text-align: right;">0.54</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">CC</td>
<td style="text-align: left;">Week 1</td>
<td style="text-align: right;">392.4</td>
<td style="text-align: right;">23.70</td>
<td style="text-align: right;">5.45</td>
<td style="text-align: right;">2.23</td>
<td style="text-align: right;">2.02</td>
<td style="text-align: right;">1.34</td>
<td style="text-align: right;">0.51</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">CC</td>
<td style="text-align: left;">Week 1</td>
<td style="text-align: right;">406.1</td>
<td style="text-align: right;">36.19</td>
<td style="text-align: right;">5.52</td>
<td style="text-align: right;">2.36</td>
<td style="text-align: right;">1.82</td>
<td style="text-align: right;">1.82</td>
<td style="text-align: right;">0.28</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">CC</td>
<td style="text-align: left;">Week 1</td>
<td style="text-align: right;">421.6</td>
<td style="text-align: right;">36.30</td>
<td style="text-align: right;">5.46</td>
<td style="text-align: right;">2.17</td>
<td style="text-align: right;">1.69</td>
<td style="text-align: right;">2.41</td>
<td style="text-align: right;">0.65</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">CC</td>
<td style="text-align: left;">Week 1</td>
<td style="text-align: right;">385.9</td>
<td style="text-align: right;">43.24</td>
<td style="text-align: right;">5.52</td>
<td style="text-align: right;">2.34</td>
<td style="text-align: right;">2.03</td>
<td style="text-align: right;">2.15</td>
<td style="text-align: right;">0.23</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">CC</td>
<td style="text-align: left;">Week 1</td>
<td style="text-align: right;">412.9</td>
<td style="text-align: right;">29.37</td>
<td style="text-align: right;">5.95</td>
<td style="text-align: right;">2.50</td>
<td style="text-align: right;">1.95</td>
<td style="text-align: right;">1.77</td>
<td style="text-align: right;">0.51</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
</section>
<section id="etude-de-type-crossover" class="level1">
<h1>Etude de type crossover</h1>
<p>Une étude croisée ou un essai croisé est une étude longitudinale dans laquelle les sujets reçoivent une séquence de traitements (ou d’expositions) différents.</p>
<section id="exemple-1" class="level3">
<h3 class="anchored" data-anchor-id="exemple-1">Exemple :</h3>
<p>Les effets comportementaux d’un programme de socialisation des chiots ont été évalués chez 58 chiots de race pure et 10 chiots croisés. Chaque sujet a été réparti au hasard dans l’un des cinq groupes : Socialisation plus formation (S &amp; T, n=12), Socialisation (n=10), Formation (n=13), Alimentation (n=12) et Contrôle (n=11). Pour chaque chiot on mesure la réponse à un ensemble de stimuli (commandes, manipulations,…). On s’intéresse à l’intéraction entre le type de stimuli (mesures répétées, effet WITHIN) et le type de programme (effet BETWEEN).</p>
<p>Bibliographie : Kersti Seksel, Evalynn J Mazurski, Alan Taylor, Puppy socialisation programs: short and long term behavioural effects, Applied Animal Behaviour Science, Volume 62, Issue 4, 1999, Pages 335-349, ISSN 0168-1591,<a href="https://doi.org/10.1016/S0168-1591(98)00232-9">doi</a>.</p>
</section>
</section>
<section id="etudes-à-effets-imbriqués" class="level1">
<h1>Etudes à effets imbriqués</h1>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<ul>
<li><p>Ces modèles sont aussi appelés modèles hierarchisés (<strong><em>nested</em></strong>).</p></li>
<li><p>Les niveaux du facteur <span class="math inline">\(B\)</span> sont similaires mais ne sont pas identiques selon les niveaux de l’autre facteur <span class="math inline">\(A.\)</span></p></li>
</ul>
</section>
<section id="exemple-2" class="level2">
<h2 class="anchored" data-anchor-id="exemple-2">Exemple :</h2>
<p>Données de la thèse d’exercice de Sarah Degand (2021) : EVALUATION DE L’IMPACT DU DILUEUR SUR LA CONCENTRATION EN PROAKAP4 DANS LE SPERME CONGELE DE BOUC : CORRELATION AVEC LA MOBILITE</p>
<p>étude la concentration de ProAKAP4 dans le sperme en fonction de la race et du bouc. Ici les boucs sont considérés par Race, donc l’effet bouc est imbriqué dans l’effet race.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"ProAKAP4_BOUC.xlsx"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Bouc<span class="ot">&lt;-</span><span class="fu">as.factor</span>(df<span class="sc">$</span>Bouc)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Race<span class="ot">&lt;-</span><span class="fu">as.factor</span>(df<span class="sc">$</span>Race)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Milieu<span class="ot">&lt;-</span><span class="fu">as.factor</span>(df<span class="sc">$</span>Milieu)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>Bouc,df<span class="sc">$</span>Race)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
    11 13
  1  9  9
  2  9  9
  3  9  9
  4  9  9
  5  0  9</code></pre>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/plan2.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">exemple de facteurs imbriqués</figcaption>
</figure>
</div>
</section>
</section>
<section id="etudes-de-type-split-plot" class="level1">
<h1>Etudes de type SPLIT-PLOT</h1>
<p>Split-plot : parcelle fractionnée Pour éviter des répétitions, souvent onéreuses, on peut utiliser la technique dite de SPLIT-PLOT.</p>
<p>Par exemple on veut tester l’effet de 3 préparations de pâtes et quatre températures de four sur la qualité visuelle d’une pâte à tarte. On veut répliquer 3 fois l’expérience.</p>
<p><strong><em>Question</em></strong> : si on veut faire une expérimentation totalement randomisée combien de préparations sont nécessaires ?</p>
<p><strong><em>Dispositif Split-Plot</em></strong> On réplique 3 fois chaque recette (plot) et on partage en 4 chaque préparation (split) et on les assigne aléatoirement à chaque température.</p>
<section id="mise-en-oeuvre" class="level2">
<h2 class="anchored" data-anchor-id="mise-en-oeuvre">Mise en oeuvre</h2>
<p>On considère deux facteurs <span class="math inline">\(A,B\)</span> ayant respectivement <span class="math inline">\(I,J\)</span> niveaux. On choisit le facteur <span class="math inline">\(A\)</span> sur lequel portera la contrainte.</p>
<ol type="1">
<li><p>Répéter <span class="math inline">\(K\)</span> fois chaque niveau <span class="math inline">\(a_i\)</span> de <span class="math inline">\(A\)</span>. On note <span class="math inline">\(R_{k,i}\)</span> ces blocs</p></li>
<li><p>Partager chaque blocc <span class="math inline">\(R_{k,i}\)</span> (plot) en <span class="math inline">\(J\)</span> sous-blocs (split) qui seront assignés aléatoirement à chaque niveau de <span class="math inline">\(B.\)</span></p></li>
</ol>
<p>On a donc <span class="math inline">\(N=I\times J \times K\)</span> essais.</p>
</section>
<section id="exemple-3" class="level2">
<h2 class="anchored" data-anchor-id="exemple-3">Exemple :</h2>
<p>Données de la thèse d’exercice de Sarah Degand (2021) : On veut regarder l’effet du dilueur sur la concentration en ProAKAP4. Les données sont disponibles ici : <a href="ProAKAP4_BOUC.xlsx">ProAKAP4</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>df<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"ProAKAP4_BOUC.xlsx"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Bouc<span class="ot">&lt;-</span><span class="fu">as.factor</span>(df<span class="sc">$</span>Bouc)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Race<span class="ot">&lt;-</span><span class="fu">as.factor</span>(df<span class="sc">$</span>Race)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Milieu<span class="ot">&lt;-</span><span class="fu">as.factor</span>(df<span class="sc">$</span>Milieu)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>Bouc,df<span class="sc">$</span>Race)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
    11 13
  1  9  9
  2  9  9
  3  9  9
  4  9  9
  5  0  9</code></pre>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/plan3.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">exemple des boucs</figcaption>
</figure>
</div>
</section>
</section>
<section id="rappel-anova-sur-données-indépendantes" class="level1">
<h1>Rappel ANOVA sur données indépendantes</h1>
<p>On reprend la base de données sur le régime des rats.</p>
<section id="modélisation-1-anova-sur-mesures-indépendantes-aggrégation-des-données-sur-time" class="level2">
<h2 class="anchored" data-anchor-id="modélisation-1-anova-sur-mesures-indépendantes-aggrégation-des-données-sur-time">Modélisation 1 : ANOVA sur mesures indépendantes (aggrégation des données sur Time)</h2>
<p>On calcule les moyennes entre la semaine 1 et la semaine 11 de toutes les variables considérées sur les rats.</p>
<p>Du côté de R : on utilise la librarie dplyr très pratique pour manipuler les données. Le site <a href="https://juba.github.io/tidyverse/10-dplyr.html" class="uri">https://juba.github.io/tidyverse/10-dplyr.html</a> constitue une très bonne introduction à ce package.</p>
<section id="le-modèle-mathématique-et-les-hypothèses-des-tests" class="level3">
<h3 class="anchored" data-anchor-id="le-modèle-mathématique-et-les-hypothèses-des-tests">Le modèle mathématique et les hypothèses des tests</h3>
<p>On considère un facteur <span class="math inline">\(A\)</span> à <span class="math inline">\(J\)</span> niveaux, le modèle est</p>
<p><span class="math display">\[
Y_{ij}=\mu+\alpha_{j}+\varepsilon_{ij},
\]</span></p>
<p>où <span class="math inline">\(Y_{ij}\)</span> est la réponse pour l’individu <span class="math inline">\(i\)</span> affecté dans le groupe <span class="math inline">\(j=1,...,J\)</span>. Les paramètres <span class="math inline">\(\alpha_j\)</span> sont appelés effets principaux du facteur <span class="math inline">\(A\)</span> on suppose que <span class="math inline">\(\sum_{j=1}^J\alpha_j=0.\)</span></p>
<p>On suppose que <span class="math inline">\(\varepsilon_{ij}\sim \mathcal N(0,\sigma^2)\)</span> (hypothèse d’homoscédasticité).</p>
<p>Il a deux questions principalement associées à ce modèle :</p>
<ul>
<li><p>l’estimation des coefficients <span class="math inline">\(\mu,\alpha_1,...,\alpha_{J-1}\)</span></p></li>
<li><p>la significativité de ces coefficients</p></li>
</ul>
<p>Pour l’estimation on utilise la méthode MCO (moindres carrés ordinaires) et on obtient</p>
<p><span class="math inline">\(\hat \mu=\frac 1{J}\sum_{j=1}^J\bar Y_j\)</span> et <span class="math inline">\(\hat \alpha_j=\bar Y_j-\hat \mu.\)</span></p>
<p>Remarque : si tous les groupes sont équilibrés on a <span class="math inline">\(\hat \mu=\overline{\overline Y}.\)</span></p>
<p>On teste deux hypothèses :</p>
<ul>
<li><p>Le facteur <span class="math inline">\(A\)</span> a un effet sur la réponse <span class="math inline">\(Y.\)</span> D’un point de vue mathématique on va tester <span class="math inline">\(H_0:\alpha_1=...=\alpha_J=0\)</span>. Le test utilisé s’appelle le test de Fisher (test Omnibus)</p></li>
<li><p>On peut être intéressé uniquement par tester l’effet d’un des niveaux de <span class="math inline">\(A\)</span> c’est à dire <span class="math inline">\(H_0:\alpha_j=0\)</span> pour l’un des niveaux <span class="math inline">\(j\)</span> de <span class="math inline">\(A\)</span>. Ce test est un test de Student.</p></li>
</ul>
<p>On va étudier par exemple les variables BW et Insulinemia.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(rats)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Rats"        "Groups"      "Time"        "BW"          "body fat"   
 [6] "Glycemia"    "Insulinemia" "Cholesterol" "TG"          "NEFA"       </code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">=</span> rats <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Rats,Groups) <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">NEFA=</span><span class="fu">mean</span>(NEFA),<span class="at">TG=</span><span class="fu">mean</span>(TG),<span class="at">C=</span><span class="fu">mean</span>(Cholesterol),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">BW=</span><span class="fu">mean</span>(BW),<span class="at">I=</span><span class="fu">mean</span>(Insulinemia)) </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(df1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Rats</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Groups</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">NEFA</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">TG</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">C</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BW</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">I</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">CC</td>
<td style="text-align: right;">0.3579423</td>
<td style="text-align: right;">1.676122</td>
<td style="text-align: right;">1.521581</td>
<td style="text-align: right;">435.20</td>
<td style="text-align: right;">2.357126</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">CC</td>
<td style="text-align: right;">0.4165651</td>
<td style="text-align: right;">1.492578</td>
<td style="text-align: right;">2.196187</td>
<td style="text-align: right;">440.60</td>
<td style="text-align: right;">2.518081</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">CC</td>
<td style="text-align: right;">0.3132758</td>
<td style="text-align: right;">1.837344</td>
<td style="text-align: right;">2.117650</td>
<td style="text-align: right;">483.05</td>
<td style="text-align: right;">2.292124</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">CC</td>
<td style="text-align: right;">0.4525670</td>
<td style="text-align: right;">2.172607</td>
<td style="text-align: right;">1.689075</td>
<td style="text-align: right;">495.00</td>
<td style="text-align: right;">2.175999</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">CC</td>
<td style="text-align: right;">0.2543409</td>
<td style="text-align: right;">1.912967</td>
<td style="text-align: right;">2.138862</td>
<td style="text-align: right;">453.15</td>
<td style="text-align: right;">2.243141</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">CC</td>
<td style="text-align: right;">0.4821821</td>
<td style="text-align: right;">1.498147</td>
<td style="text-align: right;">1.858858</td>
<td style="text-align: right;">473.80</td>
<td style="text-align: right;">2.379702</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="etude-de-leffet-régime-sur-bw" class="level3">
<h3 class="anchored" data-anchor-id="etude-de-leffet-régime-sur-bw">Etude de l’effet régime sur BW</h3>
<p>On commence par faire une représentation graphique de NEFA en fonction du groupe</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df1,<span class="fu">aes</span>(<span class="at">x=</span>Groups,<span class="at">y=</span>BW))<span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"BW en fonction du régime"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Dispo_expe_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong><em>Question</em></strong> Le regime semble t’il avoir un effet sur BW ? Quel groupe a la plus grande dispersion ? A combien d’observations correspondent les boxplots ?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">relevel</span>(df1<span class="sc">$</span>Groups,<span class="at">ref=</span><span class="st">"CC"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] CC CC CC CC CC CC LL LL LL LL LL LL FF FF FF FF FF FF LF LF LF LF LF LF
Levels: CC LL FF LF</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>modLin<span class="ot">&lt;-</span><span class="fu">lm</span>(BW<span class="sc">~</span>Groups,<span class="at">data=</span>df1)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(modLin,<span class="at">type =</span> <span class="st">"III"</span>) <span class="sc">%&gt;%</span> <span class="fu">kable</span>(<span class="at">digits=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sum Sq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">F value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">5083737.402</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3258.547</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Groups</td>
<td style="text-align: right;">309.531</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.066</td>
<td style="text-align: right;">0.977</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">31202.482</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>


</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modLin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BW ~ Groups, data = df1)

Residuals:
    Min      1Q  Median      3Q     Max 
-66.658 -28.969   0.433  24.258  73.892 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  460.242      8.063  57.084   &lt;2e-16 ***
Groups1        3.225     13.965   0.231    0.820    
Groups2       -2.083     13.965  -0.149    0.883    
Groups3        3.683     13.965   0.264    0.795    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 39.5 on 20 degrees of freedom
Multiple R-squared:  0.009823,  Adjusted R-squared:  -0.1387 
F-statistic: 0.06613 on 3 and 20 DF,  p-value: 0.9772</code></pre>
</div>
</div>
</section>
<section id="etude-de-leffet-régime-sur-la-variable-insulinemia" class="level3">
<h3 class="anchored" data-anchor-id="etude-de-leffet-régime-sur-la-variable-insulinemia">Etude de l’effet régime sur la variable Insulinemia</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df1,<span class="fu">aes</span>(<span class="at">x=</span>Groups,<span class="at">y=</span>I))<span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Insulinemia en fonction du régime"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Dispo_expe_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Les résultats du modèle d’ANOVA :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>modLin<span class="ot">&lt;-</span><span class="fu">lm</span>(I<span class="sc">~</span>Groups,<span class="at">data=</span>df1)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(modLin,<span class="at">type =</span> <span class="st">"III"</span>) <span class="sc">%&gt;%</span> <span class="fu">kable</span>(<span class="at">digits=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sum Sq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">F value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">163.156</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1276.855</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Groups</td>
<td style="text-align: right;">6.061</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">15.811</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">2.556</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>


</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modLin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = I ~ Groups, data = df1)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.67229 -0.14827 -0.05179  0.06656  1.07946 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.60733    0.07297  35.733   &lt;2e-16 ***
Groups1     -0.27964    0.12638  -2.213   0.0387 *  
Groups2     -0.27377    0.12638  -2.166   0.0426 *  
Groups3     -0.31656    0.12638  -2.505   0.0210 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3575 on 20 degrees of freedom
Multiple R-squared:  0.7034,    Adjusted R-squared:  0.6589 
F-statistic: 15.81 on 3 and 20 DF,  p-value: 1.665e-05</code></pre>
</div>
</div>
<p>On peut également réaliser des comparaisons par paires (on dit aussi tests post-hoc ou Test de Tukey) pour compléter l’analyse précédente :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>post_hoc<span class="ot">&lt;-</span><span class="fu">glht</span>(modLin,<span class="at">linfct =</span> <span class="fu">mcp</span>(<span class="st">"Groups"</span><span class="ot">=</span><span class="st">"Tukey"</span>))</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(post_hoc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Multiple Comparisons of Means: Tukey Contrasts


Fit: lm(formula = I ~ Groups, data = df1)

Linear Hypotheses:
              Estimate Std. Error t value Pr(&gt;|t|)    
LL - CC == 0  0.005868   0.206381   0.028 0.999991    
FF - CC == 0 -0.036923   0.206381  -0.179 0.997896    
LF - CC == 0  1.149596   0.206381   5.570  &lt; 1e-04 ***
FF - LL == 0 -0.042791   0.206381  -0.207 0.996741    
LF - LL == 0  1.143728   0.206381   5.542 0.000103 ***
LF - FF == 0  1.186519   0.206381   5.749  &lt; 1e-04 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- single-step method)</code></pre>
</div>
</div>
<p>Attention dans le cas de la variable TG on n’a pas fait de test post-hoc : c’était inutile étant donné que le test global de Fisher était non significatif.</p>
</section>
</section>
</section>
<section id="modélisation-à-effets-mixtes" class="level1">
<h1>Modélisation à effets mixtes</h1>
<p>Les situations décrites dans l’introduction vont être analysées en utilisant un modèle d’ANOVA à effets mixtes.</p>
<section id="etude-de-leffet-temporel-dans-létude-sur-les-rats" class="level2">
<h2 class="anchored" data-anchor-id="etude-de-leffet-temporel-dans-létude-sur-les-rats">Etude de l’effet temporel dans l’étude sur les rats</h2>
<p>Ici on va prendre la dimension temporelle des données. C’est à dire l’on modélise le fait que pour chaque rat il y a eu deux mesures de chaque propriété biochimique.</p>
<p><strong><em>Remarques</em></strong></p>
<ol type="1">
<li><p>Avec deux mesures par individu, la modélisation tenant compte de la mesure répétée est limitée à un effet aléatoire sur l’intercept du modèle.</p></li>
<li><p>Un modèle dans lequel on considère des effets fixes et des effets aléatoires s’appelle un modèle à effet mixte.</p></li>
</ol>
<section id="variable-réponse-bw" class="level3">
<h3 class="anchored" data-anchor-id="variable-réponse-bw">Variable réponse BW</h3>
<p>Le modèle</p>
<p><span class="math display">\[
BW_{ik}=\mu+\rho_k+\alpha_i+\varepsilon_{ik}
\]</span></p>
<p>où <span class="math inline">\(BW_{ik}\)</span> représente le poids corporel du rat <span class="math inline">\(k\)</span> à la semaine <span class="math inline">\(i\)</span>.</p>
<p>Ici on suppose que les rats sont prélevés aléatoirement dans une population de rats :</p>
<ol type="1">
<li><p>L’effet rat est aléatoire c’est à dire que <span class="math inline">\(\rho_k\sim \mathcal N(0,\sigma_\rho)\)</span>.</p></li>
<li><p>L’effet semaine est fixe.</p></li>
<li><p>Les variables aléatoires <span class="math inline">\(\rho_k\)</span> et <span class="math inline">\(\varepsilon_{ik}\)</span> sont indépendantes.</p></li>
</ol>
<p>Représentation graphique :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rats,<span class="fu">aes</span>(<span class="at">x=</span>Time,<span class="at">y=</span>BW))<span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"BW en fonction du temps"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Dispo_expe_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Regardons les analyses descriptives de BW en fonction de Time :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>tab<span class="ot">&lt;-</span>rats <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Time) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">BW=</span><span class="fu">mean</span>(BW))</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(tab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Time</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BW</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Week 1</td>
<td style="text-align: right;">392.1125</td>
</tr>
<tr class="even">
<td style="text-align: left;">Week 11</td>
<td style="text-align: right;">528.3708</td>
</tr>
</tbody>
</table>


</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(tab<span class="sc">$</span>BW)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 460.2417</code></pre>
</div>
</div>
<p>Dans R pour définir un modèle à effets mixtes on va utiliser le package <strong><em>lmerTest</em></strong>. Pour indiquer l’effet aléatoire rats on utilise la synthaxe (1|Rats) :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>rats<span class="sc">$</span>Rats<span class="ot">&lt;-</span><span class="fu">as.factor</span>(rats<span class="sc">$</span>Rats)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lmer</span>(BW<span class="sc">~</span>Time<span class="sc">+</span>(<span class="dv">1</span><span class="sc">|</span>Rats),<span class="at">data=</span>rats)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: BW ~ Time + (1 | Rats)
   Data: rats

REML criterion at convergence: 449.1

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-1.97913 -0.36945  0.00274  0.33073  2.48793 

Random effects:
 Groups   Name        Variance Std.Dev.
 Rats     (Intercept) 1235.3   35.15   
 Residual              269.6   16.42   
Number of obs: 48, groups:  Rats, 24

Fixed effects:
            Estimate Std. Error      df t value Pr(&gt;|t|)    
(Intercept)  460.242      7.556  23.000   60.91   &lt;2e-16 ***
Time1        -68.129      2.370  23.000  -28.75   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
      (Intr)
Time1 0.000 </code></pre>
</div>
</div>
<p>Remarques : On constate que</p>
<ol type="1">
<li><p>L’estimation de <span class="math inline">\(\mu\)</span> correspond au poids moyen des rats.</p></li>
<li><p>L’estimation de <span class="math inline">\(\sigma_\rho\)</span> est proche de l’écart type des rats.</p></li>
</ol>
<p>En effet si on aggrège les données sur les rats (moyenne des deux semaines) on a :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>R<span class="ot">&lt;-</span>rats <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Rats) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">M=</span><span class="fu">mean</span>(BW))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(R<span class="sc">$</span>M)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37.01469</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>L’estimation de l’effet temporel correspond à la différence entre la moyenne des rats et la moyenne de la semaine 1.</li>
</ol>
<p>La fonction <strong><em>anova</em></strong> permet de tester si l’effet fixe (ici semaine) est significatif <span class="math inline">\(H_0:\alpha_1=...=\alpha_I=0\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Type III Analysis of Variance Table with Satterthwaite's method
     Sum Sq Mean Sq NumDF DenDF F value    Pr(&gt;F)    
Time 222796  222796     1    23  826.51 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>La fonction <strong><em>ranova</em></strong> permet de tester si l’effet aléatoire est significatif <span class="math inline">\(H_0:\sigma_\rho=0\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ranova</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ANOVA-like table for random-effects: Single term deletions

Model:
BW ~ Time + (1 | Rats)
           npar  logLik    AIC    LRT Df Pr(&gt;Chisq)    
&lt;none&gt;        4 -224.54 457.07                         
(1 | Rats)    3 -237.42 480.84 25.768  1   3.85e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
</section>
<section id="anova-à-deux-facteurs-fixes-et-un-facteur-aléatoire" class="level2">
<h2 class="anchored" data-anchor-id="anova-à-deux-facteurs-fixes-et-un-facteur-aléatoire">ANOVA à deux facteurs fixes et un facteur aléatoire</h2>
<p>On peut ajouter l’effet régime à l’effet temporel :</p>
<p><span class="math display">\[
BW_{ijk}=\mu+\rho_k+\alpha_i+\beta_j+(\alpha\beta)_{ij}+\varepsilon_{ijk}
\]</span> Dans le modèle on a considéré une éventuelle intercation entre les deux facteurs.</p>
<p>Représentation graphique :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rats,<span class="fu">aes</span>(<span class="at">x=</span>Time,<span class="at">y=</span>BW,<span class="at">fill=</span>Groups))<span class="sc">+</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"BW en fonction du temps et du régime"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Dispo_expe_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Estimation du modèle sur R :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lmer</span>(BW<span class="sc">~</span>Groups<span class="sc">*</span>Time<span class="sc">+</span>(<span class="dv">1</span><span class="sc">|</span>Rats),<span class="at">data=</span>rats)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: BW ~ Groups * Time + (1 | Rats)
   Data: rats

REML criterion at convergence: 410.7

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-1.6167 -0.4554 -0.0118  0.4622  2.0726 

Random effects:
 Groups   Name        Variance Std.Dev.
 Rats     (Intercept) 1433     37.85   
 Residual              255     15.97   
Number of obs: 48, groups:  Rats, 24

Fixed effects:
              Estimate Std. Error      df t value Pr(&gt;|t|)    
(Intercept)    460.242      8.063  20.000  57.084   &lt;2e-16 ***
Groups1          3.225     13.965  20.000   0.231   0.8197    
Groups2         -2.083     13.965  20.000  -0.149   0.8829    
Groups3          3.683     13.965  20.000   0.264   0.7947    
Time1          -68.129      2.305  20.000 -29.558   &lt;2e-16 ***
Groups1:Time1    5.379      3.992  20.000   1.347   0.1929    
Groups2:Time1   -7.212      3.992  20.000  -1.807   0.0859 .  
Groups3:Time1    3.037      3.992  20.000   0.761   0.4556    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) Grops1 Grops2 Grops3 Time1  Gr1:T1 Gr2:T1
Groups1      0.000                                          
Groups2      0.000 -0.333                                   
Groups3      0.000 -0.333 -0.333                            
Time1        0.000  0.000  0.000  0.000                     
Groups1:Tm1  0.000  0.000  0.000  0.000  0.000              
Groups2:Tm1  0.000  0.000  0.000  0.000  0.000 -0.333       
Groups3:Tm1  0.000  0.000  0.000  0.000  0.000 -0.333 -0.333</code></pre>
</div>
</div>
<p>Remarques :</p>
<ol type="1">
<li><p>Comme précédemment l’estimation de <span class="math inline">\(\mu\)</span> correspond à la moyenne des poids corporels.</p></li>
<li><p>Dans ce modèle il y a beaucoup de coefficients correspondants aux effets principaux (Groupe et Time) et aux effets d’interaction.</p></li>
</ol>
<p>Pour tester la significativité des effets on va utiliser la fonction anova.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Type III Analysis of Variance Table with Satterthwaite's method
            Sum Sq Mean Sq NumDF DenDF  F value Pr(&gt;F)    
Groups          51      17     3    20   0.0661 0.9772    
Time        222796  222796     1    20 873.6541 &lt;2e-16 ***
Groups:Time   1100     367     3    20   1.4373 0.2616    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li><p>On commence toujours par regarder l’effet d’intercation. Il est ici non significatif ce qui signifie que l’effet du régime sur BW n’est pas différent entre la semaine 1 et la semaine 11 (<span class="math inline">\(F(3,20)=1.43, \ p=.2616\)</span>).</p></li>
<li><p>L’effet du régime n’est pas significatif (<span class="math inline">\(F(3,20)=0.0661, \ p=.9772\)</span>).</p></li>
<li><p>L’effet de la semaine est significatif (<span class="math inline">\(F(1,20)=873.65, \ p&lt;.001\)</span>).</p></li>
</ul>
<p>On peut alors envisager un modèle plus parcimonieux (retirer l’effet d’interaction), on parle de modèle additif :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lmer</span>(BW<span class="sc">~</span>Groups<span class="sc">+</span>Time<span class="sc">+</span>(<span class="dv">1</span><span class="sc">|</span>Rats),<span class="at">data=</span>rats)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: BW ~ Groups + Time + (1 | Rats)
   Data: rats

REML criterion at convergence: 428.3

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-1.99916 -0.39801  0.02781  0.31629  2.46790 

Random effects:
 Groups   Name        Variance Std.Dev.
 Rats     (Intercept) 1425.3   37.75   
 Residual              269.6   16.42   
Number of obs: 48, groups:  Rats, 24

Fixed effects:
            Estimate Std. Error      df t value Pr(&gt;|t|)    
(Intercept)  460.242      8.063  20.000  57.084   &lt;2e-16 ***
Groups1        3.225     13.965  20.000   0.231    0.820    
Groups2       -2.083     13.965  20.000  -0.149    0.883    
Groups3        3.683     13.965  20.000   0.264    0.795    
Time1        -68.129      2.370  23.000 -28.749   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
        (Intr) Grops1 Grops2 Grops3
Groups1  0.000                     
Groups2  0.000 -0.333              
Groups3  0.000 -0.333 -0.333       
Time1    0.000  0.000  0.000  0.000</code></pre>
</div>
</div>
</section>
<section id="effet-sur-insulinemia" class="level2">
<h2 class="anchored" data-anchor-id="effet-sur-insulinemia">Effet sur insulinemia</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lmer</span>(Insulinemia<span class="sc">~</span>Groups<span class="sc">+</span>Time<span class="sc">+</span>(<span class="dv">1</span><span class="sc">|</span>Rats),<span class="at">data=</span>rats)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Type III Analysis of Variance Table with Satterthwaite's method
       Sum Sq Mean Sq NumDF DenDF F value    Pr(&gt;F)    
Groups 8.8422 2.94741     3    20 15.8114 1.665e-05 ***
Time   0.0034 0.00339     1    23  0.0182    0.8939    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>On fait alors des tests post-hoc :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>post_hoc<span class="ot">&lt;-</span><span class="fu">glht</span>(mod,<span class="at">linfct =</span> <span class="fu">mcp</span>(<span class="st">"Groups"</span><span class="ot">=</span><span class="st">"Tukey"</span>))</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(post_hoc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Multiple Comparisons of Means: Tukey Contrasts


Fit: lmer(formula = Insulinemia ~ Groups + Time + (1 | Rats), data = rats)

Linear Hypotheses:
              Estimate Std. Error z value Pr(&gt;|z|)    
LL - CC == 0  0.005868   0.206381   0.028    1.000    
FF - CC == 0 -0.036923   0.206381  -0.179    0.998    
LF - CC == 0  1.149596   0.206381   5.570   &lt;1e-06 ***
FF - LL == 0 -0.042791   0.206381  -0.207    0.997    
LF - LL == 0  1.143728   0.206381   5.542   &lt;1e-06 ***
LF - FF == 0  1.186519   0.206381   5.749   &lt;1e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- single-step method)</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rats,<span class="fu">aes</span>(<span class="at">x=</span>Time,<span class="at">y=</span>Insulinemia,<span class="at">fill=</span>Groups))<span class="sc">+</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Insulimenia en fonction du temps et du régime"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Dispo_expe_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="anova-à-effets-imbriqués" class="level1">
<h1>ANOVA à effets imbriqués</h1>
<p>On reprend l’exemple sur les boucs.</p>
<p><strong><em>Question :</em></strong> Différence de concentration de ProAKAP4 en fonction de la race ?</p>
<p>Réponse en agrégeant les données</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>agreg<span class="ot">&lt;-</span>df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Race,Bouc) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">M=</span><span class="fu">mean</span>(ProAKAP4)) </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(agreg,<span class="fu">aes</span>(<span class="at">x=</span>Race,<span class="at">y=</span>M))<span class="sc">+</span><span class="fu">geom_boxplot</span>()<span class="sc">+</span><span class="fu">geom_jitter</span>(<span class="at">width=</span>.<span class="dv">05</span>,<span class="at">col=</span><span class="st">"purple"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Dispo_expe_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(agreg<span class="sc">$</span>M<span class="sc">~</span>agreg<span class="sc">$</span>Race,<span class="at">var.equal=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  agreg$M by agreg$Race
t = -0.55338, df = 7, p-value = 0.5972
alternative hypothesis: true difference in means between group 11 and group 13 is not equal to 0
95 percent confidence interval:
 -2.264237  1.405439
sample estimates:
mean in group 11 mean in group 13 
        4.262208         4.691607 </code></pre>
</div>
</div>
<p>En utilisant un modèle à effets imbriqués (plusieurs répétitions pour chauqe bouc de chaque race)</p>
<p><span class="math display">\[
ProAKAP4_{ik}=\mu+\rho_{k(i)}+\alpha_i+\varepsilon_{ik}
\]</span></p>
<p>où <span class="math inline">\(\alpha_i\)</span> est l’effet de la race <span class="math inline">\(i\)</span>, et <span class="math inline">\(\rho_{k(i)} \sim \mathcal N(0,\sigma^2_{\rho})\)</span> est l’effet du bouc <span class="math inline">\(k\)</span> de la race <span class="math inline">\(i.\)</span></p>
<p>On écrit le modèle dans R :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lmer</span>(ProAKAP4<span class="sc">~</span>Race<span class="sc">+</span>(<span class="dv">1</span><span class="sc">|</span>Bouc<span class="sc">:</span>Race),<span class="at">data=</span>df)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ranova</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>On en déduit qu’il n’y pas de différence de concentration de ProAKAP4 en fonction de la race.</p>
</section>
<section id="anova-split-plot" class="level1">
<h1>Anova split-plot</h1>
<p><strong><em>Question 1 :</em></strong></p>
<p>On agrège les données sur les répétitions (dates Ejacbouc) et le modèle devient alors</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>agreg<span class="ot">&lt;-</span>df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Ejacbouc,Milieu)<span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">M=</span><span class="fu">mean</span>(ProAKAP4))</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(agreg,<span class="fu">aes</span>(<span class="at">x=</span>Milieu,<span class="at">y=</span>M))<span class="sc">+</span><span class="fu">geom_boxplot</span>()<span class="sc">+</span><span class="fu">geom_jitter</span>(<span class="at">width=</span>.<span class="dv">05</span>,<span class="at">col=</span><span class="st">"purple"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Dispo_expe_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lmer</span>(M<span class="sc">~</span>Milieu<span class="sc">+</span>(<span class="dv">1</span><span class="sc">|</span>Ejacbouc),<span class="at">data=</span>agreg)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod,<span class="at">type=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Type III Analysis of Variance Table with Satterthwaite's method
       Sum Sq Mean Sq NumDF DenDF F value    Pr(&gt;F)    
Milieu 94.408  47.204     2    52  10.498 0.0001481 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Le mileu a donc un effet sur la concentration en ProAKAP4, on peut faire une analyse post-hoc :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>PostHoc<span class="ot">&lt;-</span><span class="fu">glht</span>(mod,<span class="at">linfct =</span> <span class="fu">mcp</span>(<span class="st">"Milieu"</span><span class="ot">=</span><span class="st">"Tukey"</span>))</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(PostHoc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Multiple Comparisons of Means: Tukey Contrasts


Fit: lmer(formula = M ~ Milieu + (1 | Ejacbouc), data = agreg)

Linear Hypotheses:
           Estimate Std. Error z value Pr(&gt;|z|)    
L - B == 0  -2.4090     0.5771  -4.174  &lt; 1e-04 ***
O - B == 0  -0.2599     0.5771  -0.450 0.894250    
O - L == 0   2.1491     0.5771   3.724 0.000613 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- single-step method)</code></pre>
</div>
</div>
<p><strong><em>Solution 2 : Split-plot</em></strong></p>
<p>Le modèle s’écrit dans ce cas</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lmer</span>(ProAKAP4<span class="sc">~</span>Milieu<span class="sc">+</span>(<span class="dv">1</span><span class="sc">|</span>Ejacbouc)<span class="sc">+</span>(<span class="dv">1</span><span class="sc">|</span>Ejacbouc<span class="sc">:</span>Bouc),<span class="at">data=</span>df)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod,<span class="at">type=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Type III Analysis of Variance Table with Satterthwaite's method
       Sum Sq Mean Sq NumDF DenDF F value    Pr(&gt;F)    
Milieu 94.408  47.204     2    52  10.498 0.0001481 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>PostHoc<span class="ot">=</span><span class="fu">glht</span>(mod,<span class="at">linfct =</span> <span class="fu">mcp</span>(<span class="st">"Milieu"</span><span class="ot">=</span><span class="st">"Tukey"</span>))</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(PostHoc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Multiple Comparisons of Means: Tukey Contrasts


Fit: lmer(formula = ProAKAP4 ~ Milieu + (1 | Ejacbouc) + (1 | Ejacbouc:Bouc), 
    data = df)

Linear Hypotheses:
           Estimate Std. Error z value Pr(&gt;|z|)    
L - B == 0  -2.4090     0.5771  -4.174  &lt; 1e-04 ***
O - B == 0  -0.2599     0.5771  -0.450 0.894254    
O - L == 0   2.1491     0.5771   3.724 0.000572 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- single-step method)</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lmer</span>(ProAKAP4<span class="sc">~</span>Race<span class="sc">+</span>Milieu<span class="sc">+</span>(<span class="dv">1</span><span class="sc">|</span>Bouc)<span class="sc">+</span>(<span class="dv">1</span><span class="sc">|</span>Race<span class="sc">:</span>Ejacbouc)<span class="sc">+</span>(<span class="dv">1</span><span class="sc">|</span>Ejacbouc<span class="sc">:</span>Bouc),<span class="at">data=</span>df,<span class="at">REML=</span>F)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod,<span class="at">type=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Type III Analysis of Variance Table with Satterthwaite's method
       Sum Sq Mean Sq NumDF  DenDF F value    Pr(&gt;F)    
Race    3.855   3.855     1 24.290  0.8902 0.3547169    
Milieu 94.408  47.204     2 54.001 10.9014 0.0001055 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ranova</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ANOVA-like table for random-effects: Single term deletions

Model:
ProAKAP4 ~ Race + Milieu + (1 | Bouc) + (1 | Race:Ejacbouc) + (1 | Ejacbouc:Bouc)
                    npar  logLik    AIC    LRT Df Pr(&gt;Chisq)
&lt;none&gt;                 8 -177.67 371.34                     
(1 | Bouc)             7 -178.37 370.74 1.3937  1     0.2378
(1 | Race:Ejacbouc)    7 -177.67 369.34 0.0000  1     1.0000
(1 | Ejacbouc:Bouc)    7 -177.67 369.34 0.0000  1     1.0000</code></pre>
</div>
</div>
<p>On peut choisir le meilleur modèle en utilisant la fonction <strong><em>step</em></strong> :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Backward reduced random-effect table:

                    Eliminated npar  logLik    AIC     LRT Df Pr(&gt;Chisq)
&lt;none&gt;                            8 -177.67 371.34                      
(1 | Race:Ejacbouc)          1    7 -177.67 369.34 0.00000  1     1.0000
(1 | Ejacbouc:Bouc)          2    6 -177.73 367.45 0.11066  1     0.7394
(1 | Bouc)                   3    5 -178.79 367.58 2.12913  1     0.1445

Backward reduced fixed-effect table:
       Eliminated Df Sum of Sq    RSS    AIC F value    Pr(&gt;F)    
Race            1  1     3.688 395.65 134.47  0.7244 0.3973315    
Milieu          0  2    94.408 490.06 147.81  9.3060 0.0002374 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Model found:
ProAKAP4 ~ Milieu</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lmer</span>(ProAKAP4<span class="sc">~</span>Race<span class="sc">+</span>Milieu<span class="sc">+</span>(<span class="dv">1</span><span class="sc">|</span>Bouc)<span class="sc">+</span>(<span class="dv">1</span><span class="sc">|</span>Ejacbouc<span class="sc">:</span>Bouc),<span class="at">data=</span>df,<span class="at">REML=</span>F)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod,<span class="at">type=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Type III Analysis of Variance Table with Satterthwaite's method
       Sum Sq Mean Sq NumDF  DenDF F value    Pr(&gt;F)    
Race    3.855   3.855     1 24.289  0.8902 0.3547190    
Milieu 94.408  47.204     2 54.000 10.9013 0.0001055 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ranova</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ANOVA-like table for random-effects: Single term deletions

Model:
ProAKAP4 ~ Race + Milieu + (1 | Bouc) + (1 | Ejacbouc:Bouc)
                    npar  logLik    AIC     LRT Df Pr(&gt;Chisq)
&lt;none&gt;                 7 -177.67 369.34                      
(1 | Bouc)             6 -178.37 368.74 1.39373  1     0.2378
(1 | Ejacbouc:Bouc)    6 -177.73 367.45 0.11066  1     0.7394</code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>